name: AppCoinsSDK
options:
  bundleIdPrefix: com.aptoide
  deploymentTarget:
    iOS: '14.0'
settings:
  base:
    SWIFT_VERSION: '5.5'
    CODE_SIGN_IDENTITY: Apple Distribution
    DEVELOPMENT_TEAM: 26RRGP4GNA
    CODE_SIGN_STYLE: Manual
    BUILD_LIBRARY_FOR_DISTRIBUTION: true
    SKIP_INSTALL: false
    SUPPORTED_PLATFORMS: iphonesimulator iphoneos
    TARGETED_DEVICE_FAMILY: 1,2
targets:
  AppCoinsSDK:
    type: framework
    platform: iOS
    sources:
    - path: Sources/AppCoinsSDK
    settings:
      base:
        INFOPLIST_FILE: Sources/AppCoinsSDK/Info.plist
        BUILD_LIBRARY_FOR_DISTRIBUTION: true
        SKIP_INSTALL: false
        SUPPORTED_PLATFORMS: iphonesimulator iphoneos
        TARGETED_DEVICE_FAMILY: 1,2
        CODE_SIGN_IDENTITY: Apple Distribution
        DEVELOPMENT_TEAM: 26RRGP4GNA
        CODE_SIGN_STYLE: Manual
    options:
      transitivelyLinkDependencies: false
    dependencies:
    - package: CryptoSwift
      product: CryptoSwift
    - package: web3swift
      product: web3swift
    - package: SkeletonUI
      product: SkeletonUI
    - package: SwiftyRSA
      product: SwiftyRSA
    - package: ActivityIndicatorView
      product: ActivityIndicatorView
    - package: DeviceKit
      product: DeviceKit
    resources:
    - path: Sources/AppCoinsSDK/Localization
      explicit: true
    frameworks: []
    postBuildScripts:
    - name: Embed Dependency Asset Bundles
      script: "\n                            # Find .bundle files\n              \
        \              BUNDLE_FILES=$(find \"${BUILT_PRODUCTS_DIR}\" -maxdepth 1 -type\
        \ d -name \"*.bundle\")\n                            # Copy .bundle files\
        \ to inside the generated framework\n                            for BUNDLE\
        \ in $BUNDLE_FILES; do\n                                rsync -av --delete\
        \ \"${BUNDLE}\" \"${BUILT_PRODUCTS_DIR}/AppCoinsSDK.framework\"\n        \
        \                    done\n                        "
    - name: Remove .framework Files From Build Folder
      script: "\n                        # Find .xcframework files\n             \
        \           XCFRAMEWORK_FILES=$(find \"${BUILT_PRODUCTS_DIR}/AppCoinsSDK.framework\"\
        \ -maxdepth 1 -type d -name \"*.framework\")\n                        # Remove\
        \ .framework files from inside AppCoinsSDK.framework\n                   \
        \     for XCFRAMEWORK in $XCFRAMEWORK_FILES; do\n                        \
        \    if [ \"$XCFRAMEWORK\" != \"${BUILT_PRODUCTS_DIR}/AppCoinsSDK.framework\"\
        \ ]; then\n                                rm -rf \"$XCFRAMEWORK\"\n     \
        \                       fi\n                        done\n               \
        \         "
packages:
  web3swift:
    url: https://github.com/web3swift-team/web3swift.git
    minorVersion: 3.2.0
  CryptoSwift:
    url: https://github.com/krzyzanowskim/CryptoSwift.git
    minorVersion: 1.5.1
  SkeletonUI:
    url: https://github.com/CSolanaM/SkeletonUI.git
    minorVersion: 2.0.1
  SwiftyRSA:
    url: https://github.com/TakeScoop/SwiftyRSA.git
    minorVersion: 1.8.0
  ActivityIndicatorView:
    url: https://github.com/exyte/ActivityIndicatorView.git
    minorVersion: 1.1.0
  DeviceKit:
    url: https://github.com/devicekit/DeviceKit.git
    minorVersion: 4.0.0
