name: AppCoinsSDK
options:
  bundleIdPrefix: com.aptoide
  deploymentTarget:
    iOS: '14.0'

settings:
  base:
    SWIFT_VERSION: '5.5'
    CODE_SIGN_IDENTITY: "iPhone Developer"
    CODE_SIGN_STYLE: "Automatic"
    BUILD_LIBRARY_FOR_DISTRIBUTION: True
    SKIP_INSTALL: False
    SUPPORTED_PLATFORMS: "iphonesimulator iphoneos"
    TARGETED_DEVICE_FAMILY: "1,2"

targets:
  AppCoinsSDK:
    type: framework
    platform: iOS
    sources: [Sources/AppCoinsSDK]
    resources: [Sources/AppCoinsSDK/Localization]
    settings:
      base:
        INFOPLIST_FILE: Sources/AppCoinsSDK/Info.plist
        BUILD_LIBRARY_FOR_DISTRIBUTION: True
        SKIP_INSTALL: False
        SUPPORTED_PLATFORMS: "iphonesimulator iphoneos"
        TARGETED_DEVICE_FAMILY: "1,2"
    options:
      transitivelyLinkDependencies: False
    dependencies:
      - framework: Sources/AppCoinsSDK/Frameworks/IndicativeLibrary.xcframework
        embed: True
      - framework: Sources/AppCoinsSDK/Frameworks/PPRiskMagnes.xcframework
        embed: True
      - package: web3swift
      - package: CryptoSwift
      - package: url-image
        product: URLImage
      - package: SkeletonUI
      - package: SwiftyRSA
        embed: True
      - package: adyen-ios
        product: Adyen
      - package: adyen-ios
        product: AdyenCard
      - package: adyen-ios
        product: AdyenComponents
      - package: adyen-ios
        product: AdyenSession
      - package: ActivityIndicatorView
      - package: DeviceKit

packages:
  web3swift:
    url: https://github.com/web3swift-team/web3swift.git
    minorVersion: 3.2.0
  CryptoSwift:
    url: https://github.com/krzyzanowskim/CryptoSwift.git
    minorVersion: 1.5.1
  url-image:
    url: https://github.com/dmytro-anokhin/url-image.git
    minorVersion: 3.0.0
  SkeletonUI:
    url: https://github.com/CSolanaM/SkeletonUI.git
    minorVersion: 2.0.1
  SwiftyRSA:
    url: https://github.com/TakeScoop/SwiftyRSA.git
    minorVersion: 1.8.0
  adyen-ios:
    url: https://github.com/Adyen/adyen-ios.git
    exactVersion: 5.12.0
  ActivityIndicatorView:
    url: https://github.com/exyte/ActivityIndicatorView.git
    minorVersion: 1.1.0
  DeviceKit:
    url: https://github.com/devicekit/DeviceKit.git
    minorVersion: 4.0.0
