name: AppCoinsSDK
options:
  bundleIdPrefix: com.aptoide
  deploymentTarget:
    iOS: '14.0'
settings:
  base:
    SWIFT_VERSION: '5.5'
    CODE_SIGN_IDENTITY: iPhone Developer
    CODE_SIGN_STYLE: Automatic
    BUILD_LIBRARY_FOR_DISTRIBUTION: true
    SKIP_INSTALL: false
    SUPPORTED_PLATFORMS: iphonesimulator iphoneos
    TARGETED_DEVICE_FAMILY: 1,2
    LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/Frameworks @loader_path/Frameworks
targets:
  AppCoinsSDK:
    type: framework
    platform: iOS
    sources:
    - Sources/AppCoinsSDK
    settings:
      base:
        INFOPLIST_FILE: Sources/AppCoinsSDK/Info.plist
        BUILD_LIBRARY_FOR_DISTRIBUTION: true
        SKIP_INSTALL: false
        SUPPORTED_PLATFORMS: iphonesimulator iphoneos
        TARGETED_DEVICE_FAMILY: 1,2
        LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/Frameworks @loader_path/Frameworks
    options:
      transitivelyLinkDependencies: false
    dependencies:
    - package: url-image
      product: URLImage
    - package: CryptoSwift
      product: CryptoSwift
    - package: web3swift
      product: web3swift
    - package: SkeletonUI
      product: SkeletonUI
    - package: SwiftyRSA
      product: SwiftyRSA
    - package: adyen-ios
      product: Adyen
    - package: adyen-ios
      product: AdyenCard
    - package: adyen-ios
      product: AdyenComponents
    - package: adyen-ios
      product: AdyenSession
    - package: ActivityIndicatorView
      product: ActivityIndicatorView
    - package: DeviceKit
      product: DeviceKit
    - framework: ./Sources/AppCoinsSDK/Frameworks/IndicativeLibrary.xcframework
      embed: true
    - framework: ./Sources/AppCoinsSDK/Frameworks/PPRiskMagnes.xcframework
      embed: true
    resources:
    - path: Sources/AppCoinsSDK/Localization
      explicit: true
    - path: $(BUILT_PRODUCTS_DIR)/Adyen_AdyenActions.bundle
      explicit: true
    - path: $(BUILT_PRODUCTS_DIR)/Web3swift_web3swift.bundle
      explicit: true
    - path: $(BUILT_PRODUCTS_DIR)/Adyen_Adyen.bundle
      explicit: true
    - path: $(BUILT_PRODUCTS_DIR)/Adyen_AdyenCard.bundle
      explicit: true
    - path: $(BUILT_PRODUCTS_DIR)/Adyen3DS2.bundle
      explicit: true
    frameworks:
    - path: $(BUILT_PRODUCTS_DIR)/IndicativeLibrary.framework
      explicit: true
      embed: true
    - path: $(BUILT_PRODUCTS_DIR)/PPRiskMagnes.framework
      explicit: true
      embed: true
    - path: $(BUILT_PRODUCTS_DIR)/Adyen3DS2.framework
      explicit: true
      embed: true
    - path: $(BUILT_PRODUCTS_DIR)/PackageFrameworks/SwiftyRSA.framework
      explicit: true
      embed: true
    postBuildScripts:
    - name: Embed Frameworks
      script: "\n            FRAMEWORKS_DIR=\"${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}\"\
        \n            EMBED_FRAMEWORKS=\n        (\"${BUILT_PRODUCTS_DIR}/IndicativeLibrary.framework\"\
        , \"${BUILT_PRODUCTS_DIR}/PPRiskMagnes.framework\", \"${BUILT_PRODUCTS_DIR}/Adyen3DS2.framework\"\
        , \"${BUILT_PRODUCTS_DIR}/PackageFrameworks/SwiftyRSA.framework\")\n     \
        \       for FRAMEWORK in \"${EMBED_FRAMEWORKS[@]}\"; do\n            if [\
        \ -d \"${FRAMEWORK}\" ]; then\n              echo \"Embedding ${FRAMEWORK}\"\
        \n              cp -R \"${FRAMEWORK}\" \"${FRAMEWORKS_DIR}\"\n           \
        \   # Modify rpath for each embedded framework to ensure it's loadable at\
        \ runtime\n              install_name_tool -add_rpath \"@loader_path/Frameworks\"\
        \ \"${FRAMEWORK}/$(basename ${FRAMEWORK%.framework})\"\n            fi\n \
        \         done\n        "
packages:
  web3swift:
    url: https://github.com/web3swift-team/web3swift.git
    minorVersion: 3.2.0
  CryptoSwift:
    url: https://github.com/krzyzanowskim/CryptoSwift.git
    minorVersion: 1.5.1
  url-image:
    url: https://github.com/dmytro-anokhin/url-image.git
    minorVersion: 3.0.0
  SkeletonUI:
    url: https://github.com/CSolanaM/SkeletonUI.git
    minorVersion: 2.0.1
  SwiftyRSA:
    url: https://github.com/TakeScoop/SwiftyRSA.git
    minorVersion: 1.8.0
  adyen-ios:
    url: https://github.com/Adyen/adyen-ios.git
    exactVersion: 5.12.0
  ActivityIndicatorView:
    url: https://github.com/exyte/ActivityIndicatorView.git
    minorVersion: 1.1.0
  DeviceKit:
    url: https://github.com/devicekit/DeviceKit.git
    minorVersion: 4.0.0
