name: Build AppCoins SDK XCFramework

on:
  push:
    branches:
      - 'release_*'
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Fetch all history for all branches and tags to handle pushes to the correct branch
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml

      - name: Set up Xcodegen
        run: brew install xcodegen

      - name: Run the build script
        run: python Scripts/build_xcframework.py

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add and Commit Changes
        run: |
          git add .
          git commit -m "Built .xcframework" || echo "No changes to commit"

      - name: Push Changes (Push and PR only)
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          # Determine the target branch based on the event type
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            TARGET_BRANCH="${{ github.event.pull_request.head.ref }}"
            REMOTE="https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
            git push "$REMOTE" HEAD:"$TARGET_BRANCH"
          else
            TARGET_BRANCH=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
            git push origin HEAD:"$TARGET_BRANCH"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}